### ISSUE TITLE
Spectator Errors

### ISSUE THREAD

**Issue by UnlimatedStone9** [jredfox/norespawnscreen#9] opened 2018-07-29 00:50 UTC
Using /kill in spectator renders the player in a half dead half alive trance, when the chat is opened its permanently open and using /kill again does nothing, an error appears saying "An unexpected error occurred while attempting to use this command"

You literally have to force close the game and possibly loose progress, not to mention large modpacks have long load times

**Comment by UnlimatedStone9** [comment] 2018-07-29 00:51
Also using commands doesn't close chat nor even remove the command from the chat

**Comment by UnlimatedStone9** [comment] 2018-07-29 00:51
/tp just jitters the player mentally too

**Comment by jredfox** [comment] 2018-07-29 00:59
unable to reproduce on demand this is a vanilla bug which can actually happen without this mod it's just more common since you skip the respawn screen

**Comment by jredfox** [comment] 2018-07-29 01:00
I could maybe investigate when it happens. Is the player not in the world or isDead in the world on client side I could maybe set a boolean on client side. Even if it's a vanilla bug could maybe get fixed?

**Comment by UnlimatedStone9** [comment] 2018-07-29 02:05
oh ok then thanks jredfox!

**Comment by UnlimatedStone9** [comment] 2018-07-29 02:07
the player basically just floats wherever they died, no matter the gamemode and teleporting them just makes them go jittery, I really don't know what is going on, commands like setblock and such don't work so I believe the player is considered as dead

**Comment by UnlimatedStone9** [comment] 2018-07-29 02:08
I noticed relauching the save resulted in a crash

**Comment by jredfox** [comment] 2018-07-29 02:49
post said crash. sounds to me like a broken mod I manually call all forge events needed and do everything to respawn the player properly

**Comment by UnlimatedStone9** [comment] 2018-07-29 14:37
If you want the crash report here it is
I believe this is the correct one

[crash-2018-07-29_02.58.36-server.txt](https://github.com/jredfox/norespawnscreen/files/2238851/crash-2018-07-29_02.58.36-server.txt)

**Comment by jredfox** [comment] 2018-07-29 22:54
Caused by: java.lang.ClassNotFoundException: com.EvilNotch.lib.minecraft.EntityUtil. class does in fact exist

Also try removing different coremods as they might be breaking forge asm

You have deleted a class and the jar is corrupt. Download the latest Evil Notch Lib

**Comment by UnlimatedStone9** [comment] 2018-07-30 00:33
Oh ok then, Thanks jredfox!

**Comment by jredfox** [comment] 2018-07-30 02:30
If you don't crash anymore let me know and I will try and figure out what's going on here. Won't be immediate since it's a minor bug and the lib needs to be brought out of beta

**Comment by jredfox** [comment] 2024-05-26 10:02
fixed in 2.0.0 re-write @UnlimatedStone9

**Closed as completed by jredfox** 2024-05-26 10:02 UTC
